### PR TITLE
Create modules for managing Grafana Cloud resources

### PR DESCRIPTION
**Pull request by avnes**
-  Add module for creating Grafana folder
- Add output for returning the id of a newly created folder
- Output the URL to a Grafana folder
- Add module for managing Grafana dashboards
- Only export the UID of teh dashboard since the id and numeric id is deprecated.
- Add module for Grafana Dashboard permissions
- Add codeowners file

### CODE REVIEW

**Comment by samidbb** [comment]
an idea maybe is to create an examples folder so we can use it to understand and test the code?
looks like we need to have the stack resource under its own folder

**Review by samidbb — COMMENTED** [review]
an idea maybe is to create an examples folder so we can use it to understand and test the code?
looks like we need to have the stack resources under its own folder

**Comment by avnes** [comment]
@samidbb There will be a separate PR for that. I am currently working on something like that in another repo.

**Review by samidbb — APPROVED** [review]
alright

**Pull request merged**
